[2022-06-29 22:56:51,268] {taskinstance.py:1149} INFO - Dependencies not met for <TaskInstance: ingest_data.save_data_task scheduled__2022-06-29T04:17:00+00:00 [failed]>, dependency 'Task Instance State' FAILED: Task is in the 'failed' state.
[2022-06-29 22:56:51,271] {local_task_job.py:101} INFO - Task is not able to be run
