[2022-06-28 18:12:43,515] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: ingest_data.save_data_task scheduled__2022-06-27T21:00:00+00:00 [queued]>
[2022-06-28 18:12:43,519] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: ingest_data.save_data_task scheduled__2022-06-27T21:00:00+00:00 [queued]>
[2022-06-28 18:12:43,519] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-28 18:12:43,519] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-06-28 18:12:43,519] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-28 18:12:43,543] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): save_data_task> on 2022-06-27 21:00:00+00:00
[2022-06-28 18:12:43,549] {standard_task_runner.py:52} INFO - Started process 11981 to run task
[2022-06-28 18:12:43,553] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'ingest_data', 'save_data_task', 'scheduled__2022-06-27T21:00:00+00:00', '--job-id', '44', '--raw', '--subdir', 'DAGS_FOLDER/CarPriceDag.py', '--cfg-path', '/tmp/tmptf8eqa1w', '--error-file', '/tmp/tmplewbe1fd']
[2022-06-28 18:12:43,554] {standard_task_runner.py:80} INFO - Job 44: Subtask save_data_task
[2022-06-28 18:12:43,633] {task_command.py:369} INFO - Running <TaskInstance: ingest_data.save_data_task scheduled__2022-06-27T21:00:00+00:00 [running]> on host DESKTOP-9B44JSS.localdomain
[2022-06-28 18:12:43,732] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=ingest_data
AIRFLOW_CTX_TASK_ID=save_data_task
AIRFLOW_CTX_EXECUTION_DATE=2022-06-27T21:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-06-27T21:00:00+00:00
[2022-06-28 18:12:43,735] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/root/airflow_env/lib/python3.8/site-packages/airflow/decorators/base.py", line 179, in execute
    return_value = super().execute(context)
  File "/root/airflow_env/lib/python3.8/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/root/airflow_env/lib/python3.8/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/root/airflow/dags/CarPriceDag.py", line 35, in save_data_task
    process(data_to_ingest_df)
TypeError: process() missing 1 required positional argument: 'server_url'
[2022-06-28 18:12:43,743] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=ingest_data, task_id=save_data_task, execution_date=20220627T210000, start_date=20220628T161243, end_date=20220628T161243
[2022-06-28 18:12:43,769] {standard_task_runner.py:92} ERROR - Failed to execute job 44 for task save_data_task (process() missing 1 required positional argument: 'server_url'; 11981)
[2022-06-28 18:12:43,808] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-06-28 18:12:43,853] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
