[2022-06-28 18:13:00,035] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: ingest_data.save_data_task manual__2022-06-28T16:12:51.072773+00:00 [queued]>
[2022-06-28 18:13:00,045] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: ingest_data.save_data_task manual__2022-06-28T16:12:51.072773+00:00 [queued]>
[2022-06-28 18:13:00,046] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-28 18:13:00,046] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-06-28 18:13:00,046] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-28 18:13:00,077] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): save_data_task> on 2022-06-28 16:12:51.072773+00:00
[2022-06-28 18:13:00,083] {standard_task_runner.py:52} INFO - Started process 12093 to run task
[2022-06-28 18:13:00,089] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'ingest_data', 'save_data_task', 'manual__2022-06-28T16:12:51.072773+00:00', '--job-id', '50', '--raw', '--subdir', 'DAGS_FOLDER/CarPriceDag.py', '--cfg-path', '/tmp/tmp8uif6rne', '--error-file', '/tmp/tmprd5ph7kq']
[2022-06-28 18:13:00,091] {standard_task_runner.py:80} INFO - Job 50: Subtask save_data_task
[2022-06-28 18:13:00,166] {task_command.py:369} INFO - Running <TaskInstance: ingest_data.save_data_task manual__2022-06-28T16:12:51.072773+00:00 [running]> on host DESKTOP-9B44JSS.localdomain
[2022-06-28 18:13:00,231] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=ingest_data
AIRFLOW_CTX_TASK_ID=save_data_task
AIRFLOW_CTX_EXECUTION_DATE=2022-06-28T16:12:51.072773+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-06-28T16:12:51.072773+00:00
[2022-06-28 18:13:00,232] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/root/airflow_env/lib/python3.8/site-packages/airflow/decorators/base.py", line 179, in execute
    return_value = super().execute(context)
  File "/root/airflow_env/lib/python3.8/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/root/airflow_env/lib/python3.8/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/root/airflow/dags/CarPriceDag.py", line 35, in save_data_task
    process(data_to_ingest_df)
TypeError: process() missing 1 required positional argument: 'server_url'
[2022-06-28 18:13:00,235] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=ingest_data, task_id=save_data_task, execution_date=20220628T161251, start_date=20220628T161300, end_date=20220628T161300
[2022-06-28 18:13:00,255] {standard_task_runner.py:92} ERROR - Failed to execute job 50 for task save_data_task (process() missing 1 required positional argument: 'server_url'; 12093)
[2022-06-28 18:13:00,264] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-06-28 18:13:00,306] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
