[2022-06-28 23:37:06,183] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: ingest_data.get_data_to_ingest_from_local_file_task scheduled__2022-06-28T16:59:51.072773+00:00 [queued]>
[2022-06-28 23:37:06,188] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: ingest_data.get_data_to_ingest_from_local_file_task scheduled__2022-06-28T16:59:51.072773+00:00 [queued]>
[2022-06-28 23:37:06,189] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-28 23:37:06,189] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-06-28 23:37:06,189] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-28 23:37:06,213] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): get_data_to_ingest_from_local_file_task> on 2022-06-28 16:59:51.072773+00:00
[2022-06-28 23:37:06,217] {standard_task_runner.py:52} INFO - Started process 25675 to run task
[2022-06-28 23:37:06,223] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'ingest_data', 'get_data_to_ingest_from_local_file_task', 'scheduled__2022-06-28T16:59:51.072773+00:00', '--job-id', '204', '--raw', '--subdir', 'DAGS_FOLDER/CarPriceDag.py', '--cfg-path', '/tmp/tmpux9etk_0', '--error-file', '/tmp/tmp0fqo5b25']
[2022-06-28 23:37:06,224] {standard_task_runner.py:80} INFO - Job 204: Subtask get_data_to_ingest_from_local_file_task
[2022-06-28 23:37:06,291] {task_command.py:369} INFO - Running <TaskInstance: ingest_data.get_data_to_ingest_from_local_file_task scheduled__2022-06-28T16:59:51.072773+00:00 [running]> on host DESKTOP-9B44JSS.localdomain
[2022-06-28 23:37:06,403] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=ingest_data
AIRFLOW_CTX_TASK_ID=get_data_to_ingest_from_local_file_task
AIRFLOW_CTX_EXECUTION_DATE=2022-06-28T16:59:51.072773+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-06-28T16:59:51.072773+00:00
[2022-06-28 23:37:06,408] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/root/airflow_env/lib/python3.8/site-packages/airflow/decorators/base.py", line 179, in execute
    return_value = super().execute(context)
  File "/root/airflow_env/lib/python3.8/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/root/airflow_env/lib/python3.8/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/root/airflow/dags/CarPriceDag.py", line 31, in get_data_to_ingest_from_local_file_task
    return fetchdata()
  File "/root/airflow/dags/CarPriceDag.py", line 68, in fetchdata
    bulk=pd.read_csv("true_car_listings.csv")
  File "/root/airflow_env/lib/python3.8/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/root/airflow_env/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 680, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/root/airflow_env/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 575, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/root/airflow_env/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 933, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/root/airflow_env/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1217, in _make_engine
    self.handles = get_handle(  # type: ignore[call-overload]
  File "/root/airflow_env/lib/python3.8/site-packages/pandas/io/common.py", line 789, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'true_car_listings.csv'
[2022-06-28 23:37:06,419] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=ingest_data, task_id=get_data_to_ingest_from_local_file_task, execution_date=20220628T165951, start_date=20220628T213706, end_date=20220628T213706
[2022-06-28 23:37:06,447] {standard_task_runner.py:92} ERROR - Failed to execute job 204 for task get_data_to_ingest_from_local_file_task ([Errno 2] No such file or directory: 'true_car_listings.csv'; 25675)
[2022-06-28 23:37:06,478] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-06-28 23:37:06,539] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
