[2022-06-28 23:49:30,030] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: ingest_data.get_data_to_ingest_from_local_file_task scheduled__2022-06-28T17:27:51.072773+00:00 [queued]>
[2022-06-28 23:49:30,035] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: ingest_data.get_data_to_ingest_from_local_file_task scheduled__2022-06-28T17:27:51.072773+00:00 [queued]>
[2022-06-28 23:49:30,035] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-28 23:49:30,035] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-06-28 23:49:30,035] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-28 23:49:30,062] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): get_data_to_ingest_from_local_file_task> on 2022-06-28 17:27:51.072773+00:00
[2022-06-28 23:49:30,068] {standard_task_runner.py:52} INFO - Started process 31407 to run task
[2022-06-28 23:49:30,070] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'ingest_data', 'get_data_to_ingest_from_local_file_task', 'scheduled__2022-06-28T17:27:51.072773+00:00', '--job-id', '249', '--raw', '--subdir', 'DAGS_FOLDER/CarPriceDag.py', '--cfg-path', '/tmp/tmpien1kv1v', '--error-file', '/tmp/tmpn890tap6']
[2022-06-28 23:49:30,071] {standard_task_runner.py:80} INFO - Job 249: Subtask get_data_to_ingest_from_local_file_task
[2022-06-28 23:49:30,116] {task_command.py:369} INFO - Running <TaskInstance: ingest_data.get_data_to_ingest_from_local_file_task scheduled__2022-06-28T17:27:51.072773+00:00 [running]> on host DESKTOP-9B44JSS.localdomain
[2022-06-28 23:49:30,220] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=ingest_data
AIRFLOW_CTX_TASK_ID=get_data_to_ingest_from_local_file_task
AIRFLOW_CTX_EXECUTION_DATE=2022-06-28T17:27:51.072773+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-06-28T17:27:51.072773+00:00
[2022-06-28 23:49:30,274] {process_utils.py:125} INFO - Sending Signals.SIGTERM to group 31407. PIDs of all processes in the group: [31407]
[2022-06-28 23:49:30,274] {process_utils.py:80} INFO - Sending the signal Signals.SIGTERM to group 31407
[2022-06-28 23:49:30,278] {taskinstance.py:1541} ERROR - Received SIGTERM. Terminating subprocesses.
[2022-06-28 23:49:30,285] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/root/airflow_env/lib/python3.8/site-packages/airflow/decorators/base.py", line 179, in execute
    return_value = super().execute(context)
  File "/root/airflow_env/lib/python3.8/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/root/airflow_env/lib/python3.8/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/root/airflow/dags/CarPriceDag.py", line 31, in get_data_to_ingest_from_local_file_task
    return fetchdata()
  File "/root/airflow/dags/CarPriceDag.py", line 68, in fetchdata
    bulk=pd.read_csv("true_car_listings.csv")
  File "/root/airflow_env/lib/python3.8/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/root/airflow_env/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 680, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/root/airflow_env/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 581, in _read
    return parser.read(nrows)
  File "/root/airflow_env/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1254, in read
    index, columns, col_dict = self._engine.read(nrows)
  File "/root/airflow_env/lib/python3.8/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 225, in read
    chunks = self._reader.read_low_memory(nrows)
  File "pandas/_libs/parsers.pyx", line 805, in pandas._libs.parsers.TextReader.read_low_memory
  File "pandas/_libs/parsers.pyx", line 861, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 847, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1952, in pandas._libs.parsers.raise_parser_error
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2022-06-28 23:49:30,291] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=ingest_data, task_id=get_data_to_ingest_from_local_file_task, execution_date=20220628T172751, start_date=20220628T214930, end_date=20220628T214930
[2022-06-28 23:49:30,316] {standard_task_runner.py:92} ERROR - Failed to execute job 249 for task get_data_to_ingest_from_local_file_task (Task received SIGTERM signal; 31407)
[2022-06-28 23:49:30,328] {process_utils.py:75} INFO - Process psutil.Process(pid=31407, status='terminated', exitcode=1, started='23:49:29') (31407) terminated with exit code 1
